### ISSUE TITLE
서버에 방 참가 요청 보내고 방 참가합니다

### ISSUE THREAD

**Issue by Kiyoung-Kim-57** [boostcampwm-2024/iOS04-PhotoGether#110]
## 🤔 작업 배경

- 생성된 방에 참가할 수 있도록 작업이 필요합니다

## 📝 작업 내용

- ✅생성된 방에 참가할 수 있도록 서버에 요청합니다
- 서버에서 방 참가 로직을 처리합니다
- 방 참가 후 서버에서 게스트에게 필요한 정보를 전달합니다

## ✔️ To-Do

- [x] 생성된 방에 참가할 수 있도록 서버에 요청 메시지 전달
- [x] 서버에서 방 참가 로직을 구현
- [ ] 방 참가 후 서버에서 게스트에게 게스트의 아이디와 참가 중인 유저 아이디 전달
