### ISSUE TITLE
의존성 트리를 개선합니다.

### ISSUE THREAD

**Issue by youn9k** [boostcampwm-2024/iOS04-PhotoGether#135]
## 🤔 작업 배경

<img width="809" alt="image" src="https://github.com/user-attachments/assets/89357851-c82c-4a22-b24b-67153d10738a">

현재 저희 앱의 의존성 트리는 위와 같습니다.
그리고 아래와 같은 문제점들이 존재합니다.
- **PhotoRoomFeature가 Data, Domain 모듈을 의존하고 있다.**
    - EditPhotoRoomViewController로 이동하기 위해 직접 생성해야했고, 그 과정에서 ViewModel을 생성하기 위해 UseCase와 Repository를 넣어줘야했기에 Data와 Domain을 의존하는 구조였습니다.
- **Network가 DomainInterface 모듈을 의존하고 있다.**
    - 아마 개발 단계에서 테스트하다가 Import  된 것 같습니다. 그냥 제거해도 문제가 없더라구요. 
- **각 Feature들이 다음 화면의 Feature를 의존하고 있다.**
    - Feature간의 결합도가 높아져 의존하고 있는 Feature에 변경사항이 생기면 해당 Feature에도 영향을 미칠 수 있는 구조였습니다.
- **FeatureTesting 모듈이 하는 역할이 없다,**
    - 위 그래프에는 넣지 않았지만, 각 FeatureDemo를 만들 때 의존하는 화면을 Mock으로 대체하여 해당 Feature에 대해서만 빠르게 테스트할 수 있도록 FeatureTesting 모듈을 두었었습니다. 하지만 사용되지 않아 제거해도 될 것 같습니다.

## ✔️ To-Do

- [ ] PhotoRoomFeature Data, Domain 모듈 의존성 제거
- [ ] Network DomainInterface 모듈 의존성 제거
- [x] FeatureTesting 모듈 제거
- [ ] #136
---
SceneDelegate에서 의존성을 생성하고 있는 이야기 -> DIContainer, Feature간 결합도 낮추기 -> 생성 패턴

### 의존성 트리 시각화 툴
https://magjac.com/graphviz-visual-editor/

```
strict digraph {
    // Domain Layer
    DomainInterface [shape="ellipse" style="filled" fillcolor="#29aeff"] // DomainInterface 색상
    Domain [shape="ellipse" style="filled" fillcolor="#29aeff"]
    Domain -> DomainInterface

    DomainTesting [shape="ellipse" style="filled" fillcolor="#29aeff"]
    DomainTesting -> DomainInterface

    // Data Layer
    Network [shape="ellipse" style="filled" fillcolor="#faba61"] // Data Layer 색상
    Network -> DomainInterface [color="#FF0000"] // 제거 필요

    Data [shape="ellipse" style="filled" fillcolor="#faba61"]
    Data -> DomainInterface
    Data -> Network

    // UI Framework Layer
    DesignSystem [shape="ellipse" style="filled" fillcolor="#00e536"] // DesignSystem 색상
    BaseFeature [shape="polygon" style="filled" fillcolor="#ffec27"] 
    BaseFeature -> DesignSystem

    // Feature Layer
    WaitingRoomFeature [shape="polygon" style="filled" fillcolor="#ffec27"] // Feature Layer 색상
    WaitingRoomFeature -> BaseFeature
    WaitingRoomFeature -> DesignSystem
    WaitingRoomFeature -> DomainInterface
    WaitingRoomFeature -> PhotoRoomFeature

    PhotoRoomFeature [shape="polygon" style="filled" fillcolor="#ffec27"]
    PhotoRoomFeature -> BaseFeature
    PhotoRoomFeature -> DesignSystem
    PhotoRoomFeature -> EditPhotoRoomFeature
    PhotoRoomFeature -> Data [color="#FF0000"] // 제거 필요
    PhotoRoomFeature -> Domain [color="#FF0000"] // 제거 필요
    PhotoRoomFeature -> DomainInterface

    EditPhotoRoomFeature [shape="polygon" style="filled" fillcolor="#ffec27"]
    EditPhotoRoomFeature -> BaseFeature
    EditPhotoRoomFeature -> DesignSystem
    EditPhotoRoomFeature -> SharePhotoFeature
    EditPhotoRoomFeature -> DomainInterface

    SharePhotoFeature [shape="polygon" style="filled" fillcolor="#ffec27"]
    SharePhotoFeature -> BaseFeature
    SharePhotoFeature -> DesignSystem
    SharePhotoFeature -> DomainInterface

    // App Layer
    // App [shape="ellipse" style="filled" fillcolor="#f44560"] // App Layer 색상
    // App -> BaseFeature
    // App -> DesignSystem
    // App -> EditPhotoRoomFeature
    // App -> Data
    // App -> Domain
    // App -> DomainInterface
    // App -> Network
    // App -> PhotoRoomFeature
    // App -> SharePhotoFeature
    // App -> WaitingRoomFeature
}
```
