### ISSUE TITLE
세션이 연결되는지 데모 앱을 통해 확인

### ISSUE THREAD

**Issue by youn9k** [boostcampwm-2024/iOS04-PhotoGether#24]
## 📝 작업 내용
Client들의 Interface를 수정하고 Demo 앱을 통해서 세션 연결을 확인한다.

## ✔️ To-Do
- [x] Demo 앱을 이용한 세션 연결 테스트
- [x] ConnectionClient Interface 구현
- [x] SignalingClient, WebRTCClient Interface 수정
