### ISSUE TITLE
Domain에 있는 Client들을 Data로 이사

### ISSUE THREAD

**Issue by Kiyoung-Kim-57** [boostcampwm-2024/iOS04-PhotoGether#61]
## 🤔 작업 배경

- 기존에 우선적으로 데이터 연결을 위해 도메인에 위치시켰던 ConnectionClient, SignalingClient, WebRTCClient들을 다시 데이터 레이어로 이동시키려 합니다

## 📝 작업 내용

- Signaling Client, WebRTCClient, ConnectionClient 전부 데이터 레이어로 이사
- 아래와 같은 구조로 변경하려고 합니다

<img src="https://github.com/user-attachments/assets/163f4512-721c-43d8-8b0e-0685770f3cee" width="100%"> 

## ✔️ To-Do

- [ ] Signaling Client 이사
- [ ] WebRTC Client 이사
- [ ] Connection Client 이사
- [ ] Connection Repository 생성

## 👀 ETC (추후 개발해야 할 것, 참고자료 등)

- 연결 요청 UseCase 생성 및 로직 구현
