### ISSUE TITLE
서버에서 방 생성하고 클라이언트에 방 정보 전달

### ISSUE THREAD

**Issue by Kiyoung-Kim-57** [boostcampwm-2024/iOS04-PhotoGether#95]
## 🤔 작업 배경

- 방을 만들어 4명의 유저가 서로 연결될 수 있도록 할 필요가 생겼습니다. 

## 📝 작업 내용
- 호스트가 서버에게 방 생성 요청을 보내면 서버에서 방을 생성 후 호스트에게 다시 전달합니다.

## ✔️ To-Do

- [ ] 호스트의 방 생성 요청을 받는다
- [ ] 호스트가 들어간 방을 생성한다
- [ ] 호스트에게 roomID와 userID를 전달한다
